version: "3"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    networks:
      - cloudflare_tunnel
    restart: unless-stopped

networks:
  cloudflare_tunnel:
    external: true
