version: "3"

services:
  speedtest:
    image: henrywhitaker3/speedtest-tracker:latest
    environment:
      TZ: America/Toronto
      OOKLA_EULA_GDPR: true
      AUTH: true
    volumes:
      - sppedtest_tracker_data:/config
    networks:
      - reverse_proxy
    restart: unless-stopped

volumes:
  sppedtest_tracker_data:
    external: true

networks:
  reverse_proxy:
    external: true
