version: "3"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - reverse_proxy
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
    external: true

networks:
  reverse_proxy:
    external: true
