version: "3"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - reverse_proxy
    volumes:
      - grafana_data:/var/lib/grafana
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: unless-stopped
    networks:
      - reverse_proxy
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

volumes:
  grafana_data:
    external: true
  influxdb_data:
    external: true

networks:
  reverse_proxy:
    external: true
