version: "3"

services:
  uptime_kuma:
    image: louislam/uptime-kuma:1-alpine
    volumes:
      - uptime_kuma_data:/app/data
    networks:
      - reverse_proxy
    restart: unless-stopped

volumes:
  uptime_kuma_data:
    external: true

networks:
  reverse_proxy:
    external: true
