version: "3"

services:
  portainer:
    image: portainer/portainer-ee:2.20.3-alpine
    environment:
      PORTAINER_LICENSE_KEY: ${PORTAINER_LICENSE_KEY}
    privileged: true
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      # - /$XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock # rootless
    ports:
      - 9443:9443
    networks:
      - reverse_proxy
    restart: unless-stopped

volumes:
  portainer_data:
    external: true

networks:
  reverse_proxy:
    external: true
