services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    volumes:
      # podman rootless mode
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock
      - ${APPDATA_PATH}/dockge:/app/data
      - ${STACKS_PATH}:${STACKS_PATH}
    environment:
      - DOCKGE_STACKS_DIR=${STACKS_PATH}
      - APP_DATA_DIR=${APPDATA_PATH}
    env_file:
      - .env
    networks:
      - reverse_proxy
networks:
  reverse_proxy:
    external: true
x-dockge:
  urls:
    - https://dockge.brodsky.club
