services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    #ports: # handled by npm
    # - 5001:5001
    volumes:
      # podman rootless mode
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - /home/vadim/appdata/dockge:/app/data
      - /home/vadim/homelab/services:/home/vadim/homelab/services
    environment:
      - DOCKGE_STACKS_DIR=/home/vadim/homelab/services
      - APP_DATA_DIR=/home/vadim/appdata
    networks:
      - reverse_proxy
networks:
  reverse_proxy:
    external: true
