version: "3"

services:
  wallabag:
    image: wallabag/wallabag:latest
    environment:
      # - POSTGRES_USER
      # - POSTGRES_PASSWORD
      - SYMFONY__ENV__DATABASE_USER
      - SYMFONY__ENV__DATABASE_PASSWORD
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_HOST=192.168.4.222
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DOMAIN_NAME=https://later.dadamix.com
      - SYMFONY__ENV__MAILER_DSN=smtp://127.0.0.1
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__SERVER_NAME="Later"
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
    networks:
      - cloudflare_tunnel
    volumes:
      - wallabag_data:/var/www/wallabag/web/assets/images
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost",
        ]
      interval: 1m
      timeout: 3s
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

volumes:
  wallabag_data:
    external: true

networks:
  cloudflare_tunnel:
    external: true
