version: "3"

services:
  wallabag:
    image: wallabag/wallabag:latest
    environment:
      SYMFONY__ENV__DATABASE_USER: ${WALLABAG_DATABASE_USER}
      SYMFONY__ENV__DATABASE_PASSWORD: ${WALLABAG_DATABASE_PASSWORD}
      SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
      SYMFONY__ENV__DATABASE_HOST: ${WALLABAG_DATABASE_HOST}
      SYMFONY__ENV__DATABASE_PORT: ${WALLABAG_DATABASE_PORT}
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DOMAIN_NAME: ${WALLABAG_DOMAIN_NAME}
      SYMFONY__ENV__MAILER_DSN: smtp://192.168.4.220:8025
      SYMFONY__ENV__FROM_EMAIL: wallabag@dadamix.com
      SYMFONY__ENV__SERVER_NAME: "Later"
      SYMFONY__ENV__FOSUSER_REGISTRATION: false
    networks:
      - cloudflare_tunnel
    volumes:
      - wallabag_data:/var/www/wallabag/web/assets/images
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost",
        ]
      interval: 1m
      timeout: 3s
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

volumes:
  wallabag_data:
    external: true

networks:
  cloudflare_tunnel:
    external: true
