version: "3"

services:
  nginxproxymanager:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_proxy_manager_data:/data
      - letsencrypt_data:/etc/letsencrypt
   environment:
      DISABLE_IPV6: true
    networks:
      - reverse_proxy
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    restart: unless-stopped

volumes:
  nginx_proxy_manager_data:
    external: true
  letsencrypt_data:
    external: true

networks:
  reverse_proxy:
    external: true
