version: "3"

services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:2.9.3
    network_mode: host
    restart: always
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: 1000
      PGID: 1000
      CF_API_TOKEN: ${CF_API_TOKEN}
      IP4_DOMAINS: jworld.dadamix.com
      PROXIED: false
