version: "3"

services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    user: "1000:1000"
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
      IP4_DOMAINS: jworld.dadamix.com
      PROXIED: false
